FROM ubuntu

RUN apt-get update -yqq
RUN apt-get install -yqq \
    curl \
    inotify-tools

# Installing docker
RUN sh -c 'curl -L https://get.docker.com/builds/$(uname -s)/$(uname -m)/docker-latest' > /usr/local/bin/docker
RUN chmod +x /usr/local/bin/docker

WORKDIR /lemin
ENTRYPOINT ["./watch.sh"]
